Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/abuscema/HPC_project/HPC/exercise_1/project_1/SBATCH/performance_test.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[thin005:2930316:0:2930316] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x7ff336d5e16e)
==== backtrace (tid:2930316) ====
 0  /lib64/libucs.so.0(ucs_handle_error+0x2e4) [0x7ff32cf5b794]
 1  /lib64/libucs.so.0(+0x29e3d) [0x7ff32cf5ce3d]
 2  /lib64/libucs.so.0(+0x2a025) [0x7ff32cf5d025]
 3  /lib64/libc.so.6(+0x1691fc) [0x7ff33898c1fc]
 4  /opt/programs/openMPI/4.1.5/lib/libopen-pal.so.40(opal_unsetenv+0x6b) [0x7ff33792f20b]
 5  /opt/programs/openMPI/4.1.5/lib/libmpi.so.40(ompi_mpi_finalize+0x8ea) [0x7ff337ac5b0a]
 6  /lib64/libpython3.11.so.1.0(+0x11ed95) [0x7ff338b1ed95]
 7  /lib64/libpython3.11.so.1.0(Py_RunMain+0x189) [0x7ff338c6f639]
 8  /lib64/libpython3.11.so.1.0(Py_BytesMain+0x3b) [0x7ff338c3652b]
 9  /lib64/libc.so.6(+0x27550) [0x7ff33884a550]
10  /lib64/libc.so.6(__libc_start_main+0x89) [0x7ff33884a609]
11  python(_start+0x25) [0x55712cebf095]
=================================
/var/spool/slurm/d/job410229/slurm_script: line 16: 2930316 Segmentation fault      (core dumped) python performance_test.py
